### ISSUE TITLE
Need to reinstance after update

### ISSUE THREAD

**Issue by LMSAas** [scottrogowski/mongita#9]
Hi,
Very nice work with the mongita project!

I have just started experimenting with it. 
I have found that if i write to a collection in one process and reads from it in another, the values when reading will not be updated without reinstance the MongitaClient. From behaviour it seems like the full db is loaded to memory? is there a function I can use to refresh?

I was testing this with MongitaClientDisk.

If I open two instances of the same db and collection in the same process the changes to the collection is reflected immediately. 

Best regards.

**Comment by scottrogowski** [comment]
Hi @LMSAas. Apologies for my delay in getting back to you.

Mongita is not process-safe and is only experimentally thread-safe. Usually, for separate processes, you would want something like a full-blown MongoDB installation. I'm curious to hear what your use case is? I might be able to add some sort of no-cache flag but would need to feel like there's a pretty good reason to do so.

Internally, data is cached to memory when it is read or written and stays that way through the life of the process (I would like to add cache eviction but I haven't yet)

As a workaround, you can do `client.close()` to clear the cache but I know it's not a great workaround.

**Comment by scottrogowski** [comment]
Fair enough. It turns out that in databases, process safety is a hard problem and is best handled through a client-server model. I'm not sure how SQLite does it internally (or, for that matter, what promises it does and does not make).

For my notes, possible fixes are:
- Adding a no_cache flag
- Actually implementing process safety
- Building a SQLite engine (which is something I've been strongly considering)

For you, I have a list of alternative embedded databases listed at the bottom of the README. I might look into UnQLite if you don't mind a different interface.

Closing for now.

**Comment by LMSAas** [comment]
Thank you for the answers and a cool project!
